version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - django_network

  web:
    build: ./app
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application"
    volumes:
      - ./app:/app
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge

    # Recolectar archivos estáticos (si es necesario)
RUN python manage.py collectstatic --noinput